### ISSUE TITLE
config.yml Problem

### ISSUE THREAD

**Issue by marcograhl** [LFeh/kratos-boilerplate#10]
Hi LFeh
When I change the title in the config.yml, than gulp breaks and i get the error message

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'src/data//.yml'

What do I do wrong? Wanted to build my Portfolio with your Boilerplate.

Thanks

**Comment by LFeh** [comment]
@marcograhl This problem seems some error when you downloaded the packages. Here works perfectly.

Delete you npm_modules and download again.

**Comment by marcograhl** [comment]
Hi thanks for your fast reply

I did 
rm -rf node_modules/
npm install

but i still get the error

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'src/data//.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at /Users/user/kratos-boilerplate-master 2/gulpfile.babel.js:115:45
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by LFeh** [comment]
Very stranged, I can try open an issue on Yaml repository. =/
