### ISSUE TITLE
Error in "npm run setup"

### ISSUE THREAD

**Issue by ribeiroevandro** [LFeh/kratos-boilerplate#12]
Hi @LFeh 
I installed Kratos and had the following error, I understood that the folder was not found. The intention to report this is to know if there is a solution you know.
```
> cp ./node_modules/flexibility/flexibility.js public/js/

cp: directory public/js does not exist

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "run" "vendors"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! kratos-boilerplate@0.0.1 vendors: `cp ./node_modules/flexibility/flexibility.js public/js/`
npm ERR! Exit status 1
```

**Comment by letanure** [comment]
try just create the folders, manually

`mkdir -p public/js`

**Comment by ribeiroevandro** [comment]
I thought the same after a while, but kept the issue open to see if there was a different solution. And the correct would be to `build` and not `public`.

**Comment by LFeh** [comment]
My mistake, sorry guys 👊
