### ISSUE TITLE
Problems generating SVG and SVG icons

### ISSUE THREAD

**Issue by ribeiroevandro** [LFeh/kratos-boilerplate#16]
When I put a `.svg` file in the`src/svg` folder the gulp task until it finds, however, it creates a folder inside the `src/svg/svg` folder and also in` build/svg` and both empty.

**Comment by LFeh** [comment]
Uhmmmmmmm, I'll check it

**Comment by LFeh** [comment]
Can you check @ribeiroevandro?

**Comment by ribeiroevandro** [comment]
Sorry for the delay, working hard... Now it works o/

**Comment by andre-mendes** [comment]
Nice @ribeiroevandro !
