### ISSUE TITLE
How can I Inject the icons.svg after the body tag?

### ISSUE THREAD

**Issue by marcograhl** [LFeh/kratos-boilerplate#9]
Hi this boilerplate is really great, but one thing I can't get my head around.
As described I want to put the svgs after my body-tag and I do not want to do it with php.
I tried the method of gulp-inject, but someone mentioned it does not work with babel.
Therefore I would be thrilled to see how I can implement that feature. 
U ask why, here is a screencast... I love the workflow https://css-tricks.com/video-screencasts/screencast-134-tour-site-progress-built-jekyll-grunt-sass-svg-system/.
He uses Jekyll to inject the svg, can i do that with pug too?
Thxs and happy coding

**Comment by LFeh** [comment]
I don't understand completely your question.

When I need inject a SVG on HTML, I use the 'include' on pug.

````
include /svg/logo.svg
````

And when I need the SVG sprites, I use:

````
svg.icon(aria-hidden='true') #[use(xlink:href='/svg/icons.svg#iconname')]
````

**Comment by marcograhl** [comment]
Hi thxs for the fast reply. I didn't know that u could include other stuff than pug files.
Thank you very much and your boilerplate rocks

**Comment by LFeh** [comment]
\o/
